/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.math.graphics.forms;

/**
 *
 * @author wason
 */
public class MainMenu extends javax.swing.JFrame
{

    /**
     * Creates new form MainMenu
     */
    public MainMenu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Title = new javax.swing.JLabel();
        PlaneImages = new javax.swing.JLabel();
        SolidImage = new javax.swing.JLabel();
        PlaneButton = new javax.swing.JButton();
        SolidButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title.setText("Geometry Project");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 210, 80));

        PlaneImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphics/forms/square-outline-256.png"))); // NOI18N
        getContentPane().add(PlaneImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 260, 250));

        SolidImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphics/forms/sugar-cube.png"))); // NOI18N
        getContentPane().add(SolidImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 140));

        PlaneButton.setText("Shape");
        getContentPane().add(PlaneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        SolidButton.setText("Solid");
        SolidButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SolidButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SolidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolidButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SolidButtonActionPerformed
    {//GEN-HEADEREND:event_SolidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolidButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlaneButton;
    private javax.swing.JLabel PlaneImages;
    private javax.swing.JButton SolidButton;
    private javax.swing.JLabel SolidImage;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
